name: hugo-remote

on:
  push:
    branches:
      - master

env:
  REMOTE: duanjiong/duanjiong.github.io.git
  DEST: public
  TOKEN: ${{ secrets.SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          # if your chosen Hugo theme is a submodule
          submodules: true
      - name: 🚀 Build and deploy
        #env:
        #  HUGO_ARGS:
        uses: duanjiong/hugo-remote@master
